import pandas as pd
from backtest import run_backtest, summarize_backtest

# Always-in-position baseline: same underlying spread series, but position=1
# every single day, no timing filter at all. Tests whether the trade has an
# unconditional edge, or whether the edge only shows up when you time entry
# and exit around the z-scored spread.
history = pd.read_csv("data/correlation_history.csv", parse_dates=["date"])
history = history.set_index("date").sort_index()

baseline_df = history[["spread"]].copy()
baseline_df["position"] = 1

print("=== Always-in-position baseline ===")
baseline_results = run_backtest(baseline_df)
baseline_summary = summarize_backtest(baseline_results)

# Tuned strategy, already generated by signal.py with ENTRY_ZSCORE=1.25, EXIT_ZSCORE=-0.5
tuned_df = pd.read_csv("data/signal_history.csv", parse_dates=["date"])
tuned_df = tuned_df.set_index("date").sort_index()

print("\n=== Tuned strategy (entry=1.25, exit=-0.5) ===")
tuned_results = run_backtest(tuned_df)
tuned_summary = summarize_backtest(tuned_results)

print("\n=== Side-by-side comparison ===")
comparison = pd.DataFrame({"always_in": baseline_summary, "tuned_timing": tuned_summary})
print(comparison.to_string())